route:
  repeat_interval: 2h
  receiver: email-1
  routes:
    - match:
        alertname: httpd_down
      receiver: email-1

    - match:
        alertname: nginx_down
      receiver: email-2

receivers:
- name: email-1
  email_configs:
  - to: service-registration@protonmail.com
    from: thysverkuylen@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "thysverkuylen@gmail.com"
    auth_identity: "thysverkuylen@gmail.com"
    auth_password: "obzefdlmxajtxeny"

- name: email-2
  email_configs:
  - to: service-registration@protonmail.com
    from: thysverkuylen@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "thysverkuylen@gmail.com"
    auth_identity: "thysverkuylen@gmail.com"
    auth_password: "obzefdlmxajtxeny"
